version: "3"
services:
  teneo-khoros-webhook:
    image: jolzee/teneo-khoros-webhook
    container_name: teneo-khoros-webhook
    ports:
      - "3000:3000"
    env_file:
      - .env
    links:
      - redis
  redis:
    image: "bitnami/redis:latest"
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./docker/redis-persistence:/bitnami/redis/data
  ngrok:
    image: "wernight/ngrok:latest"
    container_name: ngrok
    command:
      [sh, -c, "echo NGROK Admin URL http://localhost:4040 && /entrypoint.sh"]
    links:
      - teneo-khoros-webhook:http
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=teneo-khoros-webhook:3000
      - NGROK_REGION=us
      - NGROK_BINDTLS=true
